image: Visual Studio 2017

branches:
  only:
    - master

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd /D "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - mkdir -p build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=installed ..
  - cmake --build . --config Release --target package

artifacts: 
  - path: build\NormalMapper*.zip
